// <auto-generated />
using System;
using Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231011081505_InitialDbCreate")]
    partial class InitialDbCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.OverallDesign.OverallDesignParameters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatteryCapacityRequirement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("battery_capacity");

                    b.Property<string>("BatteryWeight")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("battery_weight");

                    b.Property<double>("FlightTimeRequirementInMinutes")
                        .HasColumnType("double precision");

                    b.Property<string>("Horsepower")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("horsepower");

                    b.Property<string>("MotorWeight")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motor_weight");

                    b.Property<string>("PayloadWeight")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_weight");

                    b.Property<string>("PowerRequirement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("power_required");

                    b.Property<string>("TotalDesignWeight")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("design_weight");

                    b.HasKey("Id");

                    b.ToTable("OverallDesignParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
