using Domain.EntityCalculations;
using Domain.Primitives;

namespace Domain.Entities.DetailedDesign;

public sealed class Motor(Guid id, Guid userId, string name, MeasureandQuantity voltageRating, MeasureandQuantity currentRating, MeasureandQuantity weight, MeasureandQuantity kv, double efficiency) : Entity(id)
{
    public Guid UserId { get; private set; } = userId;

    public string Name { get; private set; } = name;
    /// <summary>
    /// Voltage rating for the motor. Is used to calculate the maximum RPM's
    /// </summary>
    public MeasureandQuantity VoltageRating { get; private set; } = voltageRating;

    /// <summary>
    /// Current rating of the motor. Is used to determine Inverter max ouput current.
    /// </summary>
    public MeasureandQuantity CurrentRating { get; private set; } = currentRating;

    /// <summary>
    /// Weight of the motor.
    /// </summary>
    public MeasureandQuantity Weight { get; private set; } = weight;

    /// <summary>
    /// Revolutions per minute
    /// </summary>
    public MeasureandQuantity Rpm { get; private set; } = MechanicalCalculations.CalculateRpm(kv.Value, voltageRating);

    /// <summary>
    /// Kv determines the amount of rpm per volt.
    /// </summary>
    public MeasureandQuantity Kv { get; private set; } = kv;

    public double Efficiency { get; private set; } = efficiency;

    /// <summary>
    /// The amount of power generated per unit of weight that the motor weighs.
    /// </summary>
    public MeasureandQuantity PowerToWeightRatio { get; private set; } = ElectricCalculations.CalculatePowerToWeightRatio(voltageRating, currentRating, weight);

    /// <summary>
    /// The estimated amount of torque generated by a motor.
    /// </summary>
    public MeasureandQuantity Torque { get; private set; } = MechanicalCalculations.CalculateTorque(kv, voltageRating, currentRating, efficiency);
}
